### ISSUE TITLE
Wrong UTC time in containers?

### ISSUE THREAD

**Issue by Vvaltz** [tiangolo/full-stack-fastapi-postgresql#113]
Using Windows 10, Docker Desktop

In container:
Thu Feb 13 17:49:33 Vilnius 2020
Google says:
Thu Feb 13 18:49:33 Vilnius 2020

Tried:

apt-get update && apt-get install tzdata
ENV TZ=Europe/Vilnius
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

All other containers that use ubuntu images are OK. This is the first I encountered;

Please help ? I'm not too familiar with docker, and this is quite a problem if you ask me

**Comment by tiangolo** [comment]
I think you are getting an incorrect timezone, not an incorrect UTC time.

Hmm, whenever you deploy your container it will probably be in a datacenter that might be in a different timezone different than yours, so I'm not sure how useful it would be to assume a timezone in your container.

It would probably be better to use UTC in your code. Or if you are going to depend on timezones, it should be the timezones of your clients or timezones defined in your settings.

For example with things like:

```Python
from datetime import datetime

now = datetime.utcnow()
print(now)
```

Otherwise, please provide more info and a minimal self-contained example that shows the error.

Currently, I have no way of knowing how you are getting those dates, or how to help you debug it.

Also, it seems you created the exact same issue in 2 repos: https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/29

But it's still not clear where (in which repo) is your problem...

**Comment by Vvaltz** [comment]
Same as https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/issues/29
