### ISSUE TITLE
Open source porject database credentials

### ISSUE THREAD

**Issue by Jewcub** [tiangolo/full-stack-fastapi-postgresql#122]
How could we hide/store the database login and password if our API server will be open source?

**Comment by StephenBrown2** [comment]
All the config settings are [managed via environment variables](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/core/config.py) and loaded via docker config in the [particular .env file](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/b96d78db99d8c4f37f0df64df587ffebda4bfc56/%7B%7Bcookiecutter.project_slug%7D%7D/env-postgres.env), so you would only need to add that file to `.gitignore` to not track changes such as adding credentials.

**Comment by alexmitelman** [comment]
Probably, it would be nice to have those file in `.gitignore` by default.
Users can commit all the changes right after running `cookiecutter`.

**Comment by alexmitelman** [comment]
There are two solutions I can see here:
- naive: just edit `.gitignore` to add those files here (this will affect this repo as well)
- create a [post-generate hook](https://cookiecutter.readthedocs.io/en/1.7.0/advanced/hooks.html) that will add those files to `.gitignore` to a newly generated project.

I can jump on the implementation, just wanted to discuss it here first.

**Comment by StephenBrown2** [comment]
post-generate would probably be best, since if you edit https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.gitignore it would affect all subdirectories in this repo as well, like you said.

**Comment by tiangolo** [comment]
Yeah, it depends on each use case, if you need to hide those secrets, like in a public repo, you can add the credentials as env vars. But you have to make sure they are available in your CI for testing, in your deployment CI or infrastructure, etc.

If you use a private repo and deploy to your private cloud, then it's not a problem to have them there.

That's why I don't enforce any git behavior with those files, but you are free to add them to `.gitignore`.
