### ISSUE TITLE
How are the Jinja email templates rendered

### ISSUE THREAD

**Issue by stratosgear** [tiangolo/full-stack-fastapi-postgresql#141]
I see a `/backend/app/app/email-tempaltes/src` folder and a `/backend/app/app/email-tempaltes/build` folder which means that the email templates are somehow rendered/compiled.

Without becoming a Jinja expert (if at all possible), **where** is the magic happening here and how can I create my own templates...?

**Comment by michael0liver** [comment]
The email templates are using MJML. You can create your own at [mjml.io/try-it-live](https://mjml.io/try-it-live) <br>
 If you want the modify the existing ones you can copy the contents of the template in the **src** directory into the browser, make the modifications then click **view HTML** on the top right to see the generated HTML.

I think @tiangolo included both the template and the generated HTML so we could easily modify them.

**Comment by stratosgear** [comment]
Ooops, sorry!  I thought .mjml were some raw Jinja templates that needed rendering.

I guess a note in that raw .mjml folder of what these files are would be helpful.

Thanks, closing this.

**Comment by tiangolo** [comment]
Thanks for the help @michael0liver !

Also, if you use VS Code, you can try this extension: https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml

I wish there was a way to build MJML in Python instead of having to commit the built files, but :shrug: ...that's what we have for now.
