### ISSUE TITLE
Docker Swarm storage layer recommendations

### ISSUE THREAD

**Issue by borland667** [tiangolo/full-stack-fastapi-postgresql#164]
Hi Guys, 

I was wondering how are you solving the storage layer when using docker swarm on cloud servers that don't provide any shared storage like ebs, efs or the likes.

 I'm trying to avoid going to k8s but it looks like there is no simple solution to the storage problem for this particular case.

Hoping to get your thoughts

**Comment by chris-allnutt** [comment]
I usually I don't recommend running a postgres container.  Instead use a Cloud service provided option or a traditional postgres instance with backups etc...  for other file types leverage something like S3 or run a ceph cluster.  

You can also mount network file servers within the containers directly. 

I don't use docker swarm so maybe someone has some other suggestions for that specifically.

**Comment by danieljfarrell** [comment]
@chris-allnutt I was wondering about this also recently.

I've never deployed a cluster before. One of the thing I am worrying about would be deploying the backend and the database on different services. What do you think?

My hope would that I could use the approach here to deploy a docker swarm on Linodes (for example) as I need them.

**Comment by chris-allnutt** [comment]
@danieljfarrell for my current deployments I use an amazon RDS database with autoscaling and deploy my containers on ECS with autoscaling too so I don't have to worry about it.

**Comment by tiangolo** [comment]
Here's the thing. A shared storage layer, like a bucket, would normally not have enough performance to be used by databases.

If you need fault tolerance then it would probably be better to use a distributed DB, like MongoDB, CouchDB, Couchbase, ArangoDB, etc. If you need a SQL-like, then probably something like CockroachDB or TiDB.

But when using a standard SQL DB (e.g. PostgreSQL or MySQL) then I would make then run in a specific node using a label, so that they can always use the same volume.

Then you would add backups to that, maybe to the whole node or to the DB using a dump tool.

If it's not for DBs but for general files, then I would use [MinIO](https://docs.min.io/).

Have in mind that Kubernetes doesn't solve that problem by itself. You would still add a layer of something on top, probably running on Kubernetes.
