### ISSUE TITLE
Visiting http://localhost/api gives "Not Found"

### ISSUE THREAD

**Issue by paxcodes** [tiangolo/full-stack-fastapi-postgresql#227]
> Backend, JSON based web API based on OpenAPI: http://localhost/api/

Is this an outdated part of the "README.md"? Visiting `http://localhost/api/` gives  `{"detail": "Not Found"}`

I think this is supposed to be `http://localhost/api/v1/openapi.json` but I'm not 100% certain as I'm still learning how this cookiecutter is set up.

**Comment by StephenBrown2** [comment]
The API and all it's endpoints will be accessible under the `/api` endpoint. The docs are accessible from `/docs` or `/redoc`, if the defaults haven't been changed.

**Comment by paxcodes** [comment]
Ah. I understand it now. I misunderstood the wording in the README.

**Comment by Yunhan-Zheng** [comment]
I hit 404 Not found when visiting http://localhost/api/ after `docker-compose up -d`. `docker-compose ps` shows that my backend and celeryworker have both exited with code 1. Both complained about invalid email with errors like below 
backend_1       | EMAILS_FROM_EMAIL
backend_1       |   value is not a valid email address (type=value_error.email)
backend_1       | FIRST_SUPERUSER
backend_1       |   value is not a valid email address (type=value_error.email)
fullstack_demo_backend_1 exited with code 1

Here is the .env backend settings. Not sure if it's because I did not set SMTP.
# Backend
BACKEND_CORS_ORIGINS=["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fullstack_demo.com", "https://stag.fullstack_demo.com", "https://fullstack_demo.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]
PROJECT_NAME=fullstack_demo
SECRET_KEY=changethis
FIRST_SUPERUSER=admin@fullstack_demo.com
FIRST_SUPERUSER_PASSWORD=changethis
SMTP_TLS=True
SMTP_PORT=587
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
EMAILS_FROM_EMAIL=info@fullstack_demo.com

USERS_OPEN_REGISTRATION=False

SENTRY_DSN=

**Comment by Pranav174** [comment]
@Yunhan-Zheng I also faced the same problem. It is because of '_' in the email hostname. Remove that from the .env initialization and you should be fine.

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

Thanks for coming back and closing the issue @paxcodes  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
