### ISSUE TITLE
Invalid interpolation format @ centOs 7.6.1810

### ISSUE THREAD

**Issue by gongyaodon** [tiangolo/full-stack-fastapi-postgresql#272]
Hi, guys...

This project works fine for me when on my local dev centOs vmware(system version 7.8.2003), 
then I pack it up and sent to local server(centOs system version 7.6.1810), then terminal show error as below:
-----------------------------------------------------
[root@localhost hynews]# docker-compose build
ERROR: Invalid interpolation format for "networks" option in service "flower": "${TRAEFIK_PUBLIC_NETWORK?Variable not set}"

-----------------------------------------------------
I did search on web, and didn't get an answer to tackle it. Hope you guys can response to this issue.

thanks!

**Comment by gongyaodon** [comment]
@tiangolo

**Comment by dhruv4** [comment]
Hey @gongyaodon it looks like the issue is that the pre-installed docker-compose is outdated. Check your version. I followed this error thread: https://github.com/Mailu/Mailu/issues/853 which led me to reinstall docker and docker-compose with the official instructions here: https://docs.docker.com/engine/install/ and here: https://docs.docker.com/compose/install/

**Comment by tiangolo** [comment]
Thanks for the help here @dhruv4! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
