### ISSUE TITLE
Full Stack FastAPI /w MongoDB

### ISSUE THREAD

**Issue by echatzikyriakidis** [tiangolo/full-stack-fastapi-postgresql#305]
Hi to all!

I would like to ask if anyone knows how this is going:

https://fastapi.tiangolo.com/project-generation/#full-stack-fastapi-mongodb

I would like to use in the near future a solution like that.

Thank you and stay safe.

**Comment by kwatog** [comment]
I've had some success using fastapi_contrib with this repository as base. you might want to look into that.

**Comment by echatzikyriakidis** [comment]
OK, to my understanding is that fastapi_contrib is not a complete out-of-the-box full stack API.

I imagine you merged the MongoDB functionality https://github.com/identixone/fastapi_contrib/tree/master/fastapi_contrib/db from fastapi_contrib to full-stack-fastapi-postgresql, right?

What else from fastapi_contrib also did you use?

Thank you!

**Comment by kwatog** [comment]
I only used this library with mongodb and no, I did not take it apart. granted that I had to subclass some things (pagination, serializer) to get what I want for some things but for the most part, I used it as is. 

```
from fastapi_contrib.db.models import MongoDBModel

class MyModel(MongoDBModel):
    additional_field1: str
    optional_field2: int = 42
    title: str
    description: str

    class Meta:
        collection = "mymodel_collection"
        indexes = [
            IndexModel([("title", TEXT), ("description", TEXT)]),
       ]

```

```
class PostPaginate(BaseModel):
    count: int
    next: Optional[str]
    previous: Optional[str]
    result: List[PostSerializer.response_model]
    
class DefaultPagination(Pagination):
    default_offset = 0
    default_limit = 10
    max_offset = 1000
    max_limit = 100

@router.get("/", response_model=PostPaginate)
async def list(countrycode, pagination: DefaultPagination = Depends()):
    filter_kwargs = {}
    
    return await pagination.paginate(
        serializer_class=PostSerializer, **filter_kwargs
    )
```

take note that as the document stated, it's opinionated such that you'll have to name your model file as models.py. I did not follow this, though. Instead, I load and create indexes using my own script.

```
@app.on_event('startup')
async def startup():
    setup_mongodb(app)
    await create_indexes()
```

```
async def create_indexes():
    logging.info("creating indexes")
    await MyModel.create_indexes(). 
```

The documentation is lacking so you might need to know that you need to define the following in your env variables:
```
CONTRIB_MONGODB_DSN=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
CONTRIB_MONGODB_DBNAME=${MONGO_DB}
CONTRIB_FASTAPI_APP=app.main.app
CONTRIB_USER_MODEL=app.models.user.User
CONTRIB_APPS=["models"]
CONTRIB_APPS_FOLDER_NAME=app
```

So this works for me but to be honest, it's rough in the edges. I did try other libraries like odmantic but ultimately went with contrib primarily because of the following:

1. the concept of Serializer is similar with DRF which I'm familiar with
1. it's still motor and pymongo in the backend so querying mongodb feels natural
1. its code relatively simple to navigate

Obviously, I gutted a fair amount of codes from the postgres codebase because that's based on SQL Alchemy. I have yet to clean-up the codebase enough to share but I will in the next couple of weeks. I'll share it as fastapi+mongodb+firebase boilerplate which is based on this fullstack example.

**Comment by echatzikyriakidis** [comment]
This is great! You helped me a lot if I want to do it like you.

In case you publish fastapi+mongodb+firebase ping us! You never know we might use it!

Stay safe!

**Comment by erny** [comment]
I'd also be interested. I had a look at [odmantic](https://github.com/art049/odmantic) which seems to use the Repository Pattern (AIOEngine) (although you only use save/save_all, not add), and the documentation is quite good.  Pagination is also resolved in the (find method)[https://art049.github.io/odmantic/api_reference/engine/#odmantic.engine.AIOEngine.find] using `limit` and `skip`. I'll have a look at both.

**Comment by echatzikyriakidis** [comment]
Good! Stay safe.

**Comment by tiangolo** [comment]
I haven't been able to work on that, but once I can, I'll build it with ODMantic, now that I added the sync engine there and it can be used for both sync and async code.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
