### ISSUE TITLE
How to connect to database locally?

### ISSUE THREAD

**Issue by duz-sg** [tiangolo/full-stack-fastapi-postgresql#36]
I'm really interesting in this project, and want to get a start with this template.

However, I have a basic question regarding connecting the database inside container.

In develop environment, how do I connect to the database? I'm trying to setup a new server connection in pgAdmin at http://localhost:5050, but always get rejected:
```
Unable to connect to server:
could not connect to server: Connection refused
Is the server running on host "127.0.0.1" and accepting
TCP/IP connections on port 5432?
```
The url was 127.0.0.1:5432, database postgres, user postgres, and using the password I generated earlier. Anything I may used wrongly here?

**Comment by dmontagu** [comment]
> However, I have a basic question regarding connecting the database inside container.

If you are running the database inside a docker container, `127.0.0.1` is probably the wrong address for the database. If you want to connect from another container, you would typically connect to it by using the container's hostname in the docker network. In a project generated using the [fastapi project generator](https://github.com/tiangolo/full-stack-fastapi-postgresql), for example, it would look like `db:5432` rather than `127.0.0.1:5432`.

If you want to connect to the database from _outside_ of docker, you need to expose the database externally. This can be done by adding
```
services:
  db:
    ports:
      - '5432:5432'
```
to your dockerfile (with modifications for the service name as necessary).

The project generator linked above has some good documentation about how to use docker-compose for local development [here](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/README.md); you might find this useful.

**Comment by duz-sg** [comment]
@dmontagu Thanks, exposing db works, now I can connect to the db using 
```psql -h localhost -p 5432 -U postgres app```

As for connecting from pgAdmin, indeed, the host name is ```db```, instead of ```localhost```.
![Screenshot 2019-06-12 at 3 42 17 PM](https://user-images.githubusercontent.com/12764936/59332510-0515c880-8d29-11e9-8bfa-49b4d72c74b1.png)

**Comment by tiangolo** [comment]
Thanks @dmontagu for the help! :rocket: :cake: 

And thanks @duz-sg for reporting back and closing the issue :tada:
