### ISSUE TITLE
/start-reload.sh is missing in project generation

### ISSUE THREAD

**Issue by pramadito** [tiangolo/full-stack-fastapi-postgresql#369]
i was trying to run the debug live reloading server and notice /start-reload.sh nowhere to be found in this project  
![image](https://user-images.githubusercontent.com/13034156/115948673-a2331200-a4f9-11eb-9482-ad9c9d268be1.png)
![image](https://user-images.githubusercontent.com/13034156/115948683-afe89780-a4f9-11eb-9471-c26b843337e8.png)

**Comment by gerazenobi** [comment]
@pramadito note the instructions say: "_run the script from inside the container_". The reason you can find this script inside the container is because it comes prepackaged within the image `tiangolo/uvicorn-gunicorn-fastapi` as you can see [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/tree/master/docker-images), that is why you can't find it within the project's scaffolding.

**Comment by pramadito** [comment]
ah thanks

**Comment by tiangolo** [comment]
Thanks for the help here @gerazenobi ! 👏  🙇 

Thanks for coming back and closing the issue @pramadito  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
