### ISSUE TITLE
Use a different path for Vue frontend

### ISSUE THREAD

**Issue by yosoyubik** [tiangolo/full-stack-fastapi-postgresql#38]
Hi,

I wanted to use another path for the Vue frontend but updating the traefik rule to this:

```
frontend:
    labels:
      - traefik.frontend.rule=PathPrefix:/admin
```

gives a blank page and this error on the browser:

<img width="538" alt="Screen Shot 2019-06-12 at 3 00 25 PM" src="https://user-images.githubusercontent.com/1033194/59353570-8ec29780-8d23-11e9-88f6-0784b0107430.png">

**Comment by tiangolo** [comment]
The error in the console seems to be an error in your JavaScrpt/TypeScript more than the configuration of Traefik.

**Comment by HedgeShot** [comment]
@yosoyubik how did you fix this? I also have problem when trying to change the url for the frontend. CSS/JS files are not found since the frontend is looking for them at /css instead of /admin/css. I have no experience in vue.js so I dont know where to look for (env.BASE_URL seems like a good candidate but i cant find where it is defined).
Thanks
