### ISSUE TITLE
422 error when testing the login access token endpoint

### ISSUE THREAD

**Issue by awmar1** [tiangolo/full-stack-fastapi-postgresql#431]
I am using this project from a python client and I have endpoints with authorization my issue is when I try to send a request to the `access-token` endpoint it returns a 422 error 

this is the code for the request
```
def get_auth_token():
    login_endpoint = BASE_URL + 'login/access-token'

    login_data = {
        'username': 'email@mysite.com',
        'password': 'changethis',
    }

    r = requests.post(login_endpoint, data=login_data, headers=headers)

    print(r.text)
    print(r.status_code)
    print(r.json)
    auth_token = result['token_type'] + ' ' + result['access_token']

    return auth_token
```

this is the response text with 422 status code
```
{
"detail":
[{"loc":
  ["body","username"],
  "msg":"field required",
  "type":"value_error.missing"}
,{"loc":
["body","password"],
"msg":"field required",
"type":"value_error.missing"}]
}
```
edit: I have my headers set outside the function

**Comment by dmitrybabanovforreal** [comment]
I don't see your headers that are coming from the other part of the code, but are you sure your headers don't have `'Content-Type': 'application/json'` in them?

Because if they do, your FastAPI app expects a json string with login data. And since you pass login data to `data=` parameter, your request sends the login data as `x-www-form-urlencoded` data without any `json` data.

I suggest you remove `'Content-Type'` header from your `headers` completely. Because `requests` module handles this header for you depending on whether you provided data to the `data=` parameter or the `json=` parameter in the function call.

**Comment by awmar1** [comment]
Thanks! 
indeed that was the issue

**Comment by aldomatus** [comment]
for example: 
```
payload = "grant_type=&username=string&password=string&client_id=&client_secret="

    response = client.post(
        "/login",
        headers={'Content-Type': 'application/x-www-form-urlencoded', 'accept': 'application/json'},
        data=payload,
    )
```
