### ISSUE TITLE
Add hactoberfest tag to the repo

### ISSUE THREAD

**Issue by alia5gar** [tiangolo/full-stack-fastapi-postgresql#482]
It would be awesome if we can add **hactoberfest** tag to the repo this will bring in more contributions
especially small enhancements that are easier to perform on such boilerplate repository for people who are trying to start with opensource

**Comment by ktnr** [comment]
Pull-requests on this repo have not been merged in months. There is a fork with recent contributions: https://github.com/pyb4430/full-stack-fastapi-postgresql

**Comment by tiangolo** [comment]
Unfortunately adding the Hacktoberfest label to the whole repo brings a lot of spam PRs. I've been adding `hacktoberfest-accepted` to accepted PRs so people can get the benefits, but adding the label to the repo increases the amount of small and, in many cases, invalid or incomplete PRs. And right now I need to be able to focus on the ones already there and on adding features and fixing things.

In many cases those small and incomplete PRs take up more time reviewing and adjusting than writing the whole thing from scratch, so I've been having to avoid that.

I haven't updated much here on this repo because I wanted to finish some things in SQLModel first, I built SQLModel for this repo, and I want to refactor everything and integrate it, but I haven't had the time, and I haven't been able to finish the things I had pending on SQLModel first. But anyway, hopefully soon.
