### ISSUE TITLE
Consider adding wemake-python-styleguide

### ISSUE THREAD

**Issue by sobolevn** [tiangolo/full-stack-fastapi-postgresql#92]
Hi, thanks a lot for building this project! It is a great start for new projects.

Currently this project support both frontend and backend parts.
Frontend part uses `eslint` and `npm run lint` to run a linting process.
But, for some reason backend part misses that.

I suggest to add a linter for backend part as well.
I propose to add `wemake-python-styleguide`. It is the strictest python linter out there.
It contains a lot of rules, checks, and plugins. And inside it just a good old `flake8` tool.
So, it can be easily integrated with editors and other tools.

Link: https://github.com/wemake-services/wemake-python-styleguide
Docs: https://wemake-python-stylegui.de

If you like it, I can submit a PR.

**Comment by sobolevn** [comment]
Related #121

**Comment by tiangolo** [comment]
Thanks for the proposal!

I would like to use the same linters/formatters as in FastAPI and Typer. A combination of Black, Flake8, Autoflake, Isort, etc.

I prefer not to have the strictest linter available as that would impose a heavy burden for developers to follow. For example, mccabe dislikes long functions, even though considering a long function more complex than the same logic divided into a bunch of functions that go in the same place for the same logic but are scattered and can't be followed sequentially, could be debatable.

The same way, I wouldn't recommend the strictest Mypy rules (e.g. `disallow-untyped-defs`) for developers using FastAPI although I have them for FastAPI's own code.

Having strict rules, types, format, for a third-party library used by developers (e.g. FastAPI) makes sure they can use it easily. For example, having types declared for functions.

But there is no advantage in requiring that a user/developer adds return types to functions that are going to be called by FastAPI, as the developer will almost never call that code directly, there's no benefit in typing that. The same way, too strict rules can be impossible to follow, and then the warnings end up just adding "noise" to the linting process :disappointed: 

The great thing about Black, Autoflake, Isort (combined with Flake8 and Mypy) is that they take care of auto-formatting everything. There's no need to manually fix most of the warnings, as many of them are auto-fixed by running the formatters. :rocket:

**Comment by sobolevn** [comment]
OK, fair enough! I agree that easier adoption requires lower entry barrier that tools like this one increases. 

Anyway, thanks a lot for you detailed answer! 

Maybe we can list it somewhere in the docs?

**Comment by tiangolo** [comment]
Thanks for understanding.

Actually, I would prefer not to add it to the docs while I'm recommending a different setup, as it would be confusing for users.

But thanks for the interest!

I'm gonna close this issue now, but feel free to add more comments or new issues.
